name: task3

on: push
jobs:
   build-containers:
   name: Build Docker container image
   runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - uses: docker/build-push-action@v1
    with: 
    username 
