version: '3'

services:
 web:
     image: task3
     container_name: testtask3
     ports: 
     - 80:80
     environment:
      - DEVOPS=${DEVOPS}
     #env_file:
     #- .env

 web1:
     image: task3
     container_name: web1
     ports:
     - 90:90
     environment:
      - DEVOPS=${DEVOPS}
     #env_file:
     #- .env
 web2:
     image: task3
     container_name: web2
     ports:
     - 123:123
     environment:
      - DEVOPS=${DEVOPS}
     #env_file:
     #- .env
 web3:
     image: task3
     container_name: web3
     ports:
     - 220:220
     environment:
      - DEVOPS=${DEVOPS}
     #env_file:
     #- .env
 web4:
     image: task3
     container_name: web4
     ports:
     - 540:540
     environment:
      - DEVOPS=${DEVOPS}
     #env_file:
     #- .env
 web5:
     image: task3
     container_name: web5
     ports:
     - 633:633
     environment:
      - DEVOPS=${DEVOPS}
     #env_file:
     #- .env


   
 java:
    image: 0ea726542de5
    restart: always
    depends_on:
      - db

 db: 
   image: postgres:11.4-alpine
   container_name: postgres
   ports: 
   - 5432:5432
   volumes: 
   - ./pg_data:/var/lib/postgresql/data/pgdata

