---
- hosts: aws
  become: true
  tasks:
    - name: Install Python
      yum: name=python state=latest
    
    - name: install pip
      yum: name=python-pip state=latest

    - name: install Docker
      yum: name=Docker state=latest


    - name: assicurati che docker sia attivo
      service:
         name: docker
         state: started
         enabled: yes
 
    - name: restart docker
      service: 
         name: docker 
         state: restarted
